require "spec_helper"

RSpec.describe "A user", :type => :model do

  it "- Can be saved" do
    user = User.create(name: "Jean", email: "jean@gmail.com", password: "password")
    user.save!

    found = User.last
    expect(found.name).to eq("Jean")
    expect(found.email).to eq("jean@gmail.com")
  end

  it "- Requires a name, an email and a password" do
    user = User.new
    expect(user.valid?).to eq(false)

    user.name = "Clement"
    expect(user.valid?).to eq(false)

    user.email = "r@rshow.com"
    expect(user.valid?).to eq(false)

    user.password = "password"
    expect(user.valid?).to eq(true)

  end

  it "- Requires a somewhat valid email" do
    user = User.new(name: "Jean" , password: "jesuislepassword" )
    expect(user.valid?).to eq(false)

    user.email = "rigby"
    expect(user.valid?).to eq(false)

    user.email = "rigby@rshow"
    expect(user.valid?).to eq(false)

    user.email = "rigby@rssshow.com"

    expect(user.valid?).to eq(true)
  end

  it "- Requires more than 6 caracteres for his password" do
    user = User.new(name: "Jean", email: "rigby@rssshow.com" )
    expect(user.valid?).to eq(false)

    user.password = "12345"
    expect(user.valid?).to eq(false)

    user.password = "Aze12"
    expect(user.valid?).to eq(false)

    user.password = "Aze124"

    expect(user.valid?).to eq(true)
  end

  it "- Cant have the same email as another user" do
    user = User.create(name: "Jean" , email: "m@rshow.com" , password: "jesuislepassword")
    expect(user.valid?).to eq(true)

    other_user = User.create(name: "Jean", email: "m@rshow.com" , password: "jesuislepassword")
    expect(other_user.valid?).to eq(false)
  end

  it "- if he enter an url, have to be a real url" do
    user = User.create(name: "Jeaqcn" , email: "m@rshoqscqscw.com" , password: "jesuislepassword", url: "")
    expect(user.valid?).to eq(true)

    other_user = User.create(name: "zC", email: "m@rshqcsow.com" , password: "jesuislepassword", url: "Salut")
    expect(other_user.valid?).to eq(false)

    otherone_user = User.create(name: "BF", email: "m@rshqscqcow.com" , password: "jesuislepassword", url: "https://www.facebook.com/")
    expect(otherone_user.valid?).to eq(true)

  end

   it "- Cant have the same pseudo as another usere" do
    user = User.create(name: "Jean" , email: "m@rshsscsow.com" , password: "jesuislepassword")
    expect(user.valid?).to eq(true)

    other_user = User.create(name: "Jean", email: "mscsc@rshow.com" , password: "jesuislepassword")
    expect(other_user.valid?).to eq(false)
  end

  it "- have an encoded password" do
    user = User.create(name: "Jean", email: "m@rshow.com" , password: "jesuislepassword")
    expect(user.valid?).to eq(true)


    userFromDB = User.last
    expect(userFromDB.name).to eq("Jean")
    expect(userFromDB.email).to eq("m@rshow.com")

    expect(userFromDB.password == user.password).to eq(false)
  end

  it "- The file selected have to be a image format " do
    user = User.new(name: "Jean Pierre", email: "m@rshow.com" , password: "jesuislepassword")
    expect(user.valid?).to eq(true)

    user.avatar = Rack::Test::UploadedFile.new(Rails.root.join('spec/fixtures/1f1e6.svg'), 'image/svg');
    expect(user.valid?).to eq(false)

    user.avatar = Rack::Test::UploadedFile.new(Rails.root.join('spec/fixtures/games.html'), 'file/html');
    expect(user.valid?).to eq(false)

    user.avatar = Rack::Test::UploadedFile.new(Rails.root.join('spec/fixtures/potté.jpg'), 'image/jpg');
    expect(user.valid?).to eq(true)

    user.avatar = Rack::Test::UploadedFile.new(Rails.root.join('spec/fixtures/tyrion.png'), 'image/png');
    expect(user.valid?).to eq(true)
  end

  it "- Requires a name,and a slug, generated by the name" do
    user = User.create(name: "Jean Pierre", email: "m@rshow.com" , password: "jesuislepassword")

    userFromDB = User.last
    expect(userFromDB.name).to eq("Jean Pierre")
    expect(userFromDB.slug).to eq("jean_pierre")
  end

  it "- Can have a description" do
    user = User.create(name: "Jean Pierre", email: "m@rshow.com" , password: "jesuislepassword", desc: "Lorem ipsum ma description")

    expect(user.desc).to eq("Lorem ipsum ma description")
  end

  it "- The Slug generated have to be unique" do
    user = User.create(name: "Jéan Pierre", email: "m@rshow.com" , password: "jesuislepassword")
    userFromDB = User.last
    expect(userFromDB.name).to eq("Jéan Pierre")
    expect(userFromDB.slug).to eq("j_an_pierre")

    other_user = User.create(name: "Jàan Pierre", email: "qscm@rshow.com" , password: "jesuislepassword")

    expect(other_user.valid?).to eq(false)

  end

end
